package br.com.bonabox.business.dataproviders.impl;


import br.com.bonabox.business.api.filter.DataMDC;
import br.com.bonabox.business.dataproviders.EnviarNotificacaoDataProvider;
import br.com.bonabox.business.dataproviders.ex.DataProviderException;
import br.com.bonabox.business.util.WebClientBonabox;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.client.WebClient;

import javax.mail.internet.MimeMessage;
import java.time.LocalDateTime;
import java.util.Map;
import java.util.UUID;

@Component("email")
public class EnviarEmailDataProviderImpl implements EnviarNotificacaoDataProvider {

	@Autowired
	private JavaMailSender emailSender;

	private final Logger logger = LoggerFactory.getLogger(this.getClass());
	
	@Autowired
	private WebClientBonabox<Notificacao> webClientBonabox;
	
	@Qualifier("interno-bonabox")
	@Autowired
	private WebClient webClient;
	
	@Override
	public boolean enviar(String texto, String numeroTelefone) throws DataProviderException {

		String destinatario = "";
		try {
			
			String [] array = texto.split("#");
			
			String assunto = array[0];
			destinatario = numeroTelefone;
			String saudacao = array[1];
			String nomeTransportadora = array[2];
			String dataDeposito = array[3];
			String nomeCondominio = array[4];
			String nomeBox = array[5];
			String codigoRetirada = array[6];
			String qrCodeBase64 = array[7];
			String mensagemInicial = array[8];
			
            MimeMessage mail = emailSender.createMimeMessage();

            MimeMessageHelper helper = new MimeMessageHelper( mail, true, "UTF-8");
            helper.setTo(destinatario);
            helper.setSubject(assunto);

String bodyEmail = "<html>\r\n"
		+ "\r\n"
		+ "<head></head>\r\n"
		+ "\r\n"
		+ "<body style=\"\r\n"
		+ "    margin-right: 0px;\r\n"
		+ "    margin-top: 0px;\r\n"
		+ "    margin-left: 0px;\r\n"
		+ "    margin-bottom: 0px;\r\n"
		+ "\">\r\n"
		+ "   <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" name=\"x_bmeMainBody\" bgcolor=\"#e6e6e8\"\r\n"
		+ "      style=\"background-color:rgb(230,230,232)\">\r\n"
		+ "      <tbody>\r\n"
		+ "         <tr>\r\n"
		+ "            <td width=\"100%\" valign=\"top\" align=\"center\">\r\n"
		+ "               <table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" name=\"x_bmeMainColumnParentTable\"\r\n"
		+ "                  style=\"border-collapse:separate; border-spacing:0px\">\r\n"
		+ "                  <tbody>\r\n"
		+ "                     <tr>\r\n"
		+ "                        <td name=\"x_bmeMainColumnParent\"\r\n"
		+ "                           style=\"border-collapse:separate; border-color:transparent; border-width:0px; border-style:none; border-radius:0px; overflow:visible; border-spacing:0px\">\r\n"
		+ "                           <table name=\"x_bmeMainColumn\" class=\"x_bmeHolder x_bmeMainColumn\" cellspacing=\"0\"\r\n"
		+ "                              cellpadding=\"0\" border=\"0\" align=\"center\"\r\n"
		+ "                              style=\"max-width:600px; overflow:visible; border-color:transparent; border-width:0px; border-style:none; border-radius:0px; border-collapse:separate; border-spacing:0px\">\r\n"
		+ "                              <tbody>\r\n"
		+ "                                 <tr id=\"x_section_1\" class=\"x_flexible-section\">\r\n"
		+ "                                    <td width=\"100%\" class=\"x_blk_container x_bmeHolder\" name=\"x_bmePreHeader\"\r\n"
		+ "                                       valign=\"top\" align=\"center\" bgcolor=\"\"\r\n"
		+ "                                       style=\"color:rgb(102,102,102); border:0px none transparent\"></td>\r\n"
		+ "                                 </tr>\r\n"
		+ "                                 <tr>\r\n"
		+ "                                    <td width=\"100%\" class=\"x_bmeHolder\" valign=\"top\" align=\"center\"\r\n"
		+ "                                       name=\"x_bmeMainContentParent\"\r\n"
		+ "                                       style=\"border-color:transparent; border-radius:15px; border-collapse:separate; border-spacing:0px; border-width:0px; border-style:none; overflow:hidden\">\r\n"
		+ "                                       <table name=\"x_bmeMainContent\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\r\n"
		+ "                                          border=\"0\" align=\"center\"\r\n"
		+ "                                          style=\"border-radius:0px; border-collapse:separate; border-spacing:0px; overflow:visible; border-color:transparent; border-width:0px; border-style:none\">\r\n"
		+ "                                          <tbody>\r\n"
		+ "                                             <tr id=\"x_section_3\" class=\"x_flexible-section\" style=\"\">\r\n"
		+ "                                                <td width=\"100%\" class=\"x_blk_container x_bmeHolder x_bmeBody\"\r\n"
		+ "                                                   name=\"x_bmeBody\" valign=\"top\" align=\"center\" bgcolor=\"#ffffff\"\r\n"
		+ "                                                   style=\"color:rgb(56,56,56); border-left-color:rgba(0,0,0,0); border-right-color:rgba(0,0,0,0); border-bottom-color:rgba(0,0,0,0); background-color:rgb(255,255,255)\">\r\n"
		+ "                                                   <div id=\"x_dv_6\" class=\"x_blk_wrapper\" style=\"\">\r\n"
		+ "                                                      <table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"\r\n"
		+ "                                                         class=\"x_blk\" name=\"x_blk_image\">\r\n"
		+ "                                                         <tbody>\r\n"
		+ "                                                            <tr>\r\n"
		+ "                                                               <td>\r\n"
		+ "                                                                  <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\r\n"
		+ "                                                                     border=\"0\">\r\n"
		+ "                                                                     <tbody>\r\n"
		+ "                                                                        <tr>\r\n"
		+ "                                                                           <td align=\"left\" class=\"x_bmeImage\"\r\n"
		+ "                                                                              style=\"border-collapse:collapse; padding:20px; background-color:rgb(239,249,246); border-style:solid; border-color:rgb(0,0,0); border-width:0px\">\r\n"
		+ "                                                                              <img data-imagetype=\"External\"\r\n"
		+ "                                                                                 src=\"https://newsafe.com.br/bonabox/logo_v2.png\"\r\n"
		+ "                                                                                 width=\"114.3\" alt=\"\" border=\"0\"\r\n"
		+ "                                                                                 class=\"x_keep-custom-width\"\r\n"
		+ "                                                                                 style=\"max-width:114.3px; display:block; border-radius:0px\">\r\n"
		+ "                                                                           </td>\r\n"
		+ "                                                                        </tr>\r\n"
		+ "                                                                     </tbody>\r\n"
		+ "                                                                  </table>\r\n"
		+ "                                                               </td>\r\n"
		+ "                                                            </tr>\r\n"
		+ "                                                         </tbody>\r\n"
		+ "                                                      </table>\r\n"
		+ "                                                   </div>\r\n"
		+ "                                                   <div id=\"x_dv_10\" class=\"x_blk_wrapper\" style=\"\">\r\n"
		+ "                                                      <table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"\r\n"
		+ "                                                         class=\"x_blk\" name=\"x_blk_divider\" style=\"\">\r\n"
		+ "                                                         <tbody>\r\n"
		+ "                                                            <tr>\r\n"
		+ "                                                               <td class=\"x_tblCellMain\" style=\"padding:0px 0px 10px\">\r\n"
		+ "                                                                  <table class=\"x_tblLine\" cellspacing=\"0\"\r\n"
		+ "                                                                     cellpadding=\"0\" border=\"0\" width=\"100%\"\r\n"
		+ "                                                                     style=\"border-top:3px solid rgb(11,196,165); min-width:1px\">\r\n"
		+ "                                                                     <tbody>\r\n"
		+ "                                                                        <tr>\r\n"
		+ "                                                                           <td><span></span></td>\r\n"
		+ "                                                                        </tr>\r\n"
		+ "                                                                     </tbody>\r\n"
		+ "                                                                  </table>\r\n"
		+ "                                                               </td>\r\n"
		+ "                                                            </tr>\r\n"
		+ "                                                         </tbody>\r\n"
		+ "                                                      </table>\r\n"
		+ "                                                   </div>\r\n"
		+ "                                                   <div id=\"x_dv_14\" class=\"x_blk_wrapper\" style=\"\">\r\n"
		+ "                                                      <table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"\r\n"
		+ "                                                         class=\"x_blk\" name=\"x_blk_text\">\r\n"
		+ "                                                         <tbody>\r\n"
		+ "                                                            <tr>\r\n"
		+ "                                                               <td>\r\n"
		+ "                                                                  <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"\r\n"
		+ "                                                                     width=\"100%\" class=\"x_bmeContainerRow\">\r\n"
		+ "                                                                     <tbody>\r\n"
		+ "                                                                        <tr>\r\n"
		+ "                                                                           <th class=\"x_tdPart\" valign=\"top\"\r\n"
		+ "                                                                              align=\"center\">\r\n"
		+ "                                                                              <table cellspacing=\"0\" cellpadding=\"0\"\r\n"
		+ "                                                                                 border=\"0\" width=\"600\" name=\"x_tblText\"\r\n"
		+ "                                                                                 class=\"x_tblText\" align=\"left\"\r\n"
		+ "                                                                                 style=\"float:left; background-color:transparent\">\r\n"
		+ "                                                                                 <tbody>\r\n"
		+ "                                                                                    <tr>\r\n"
		+ "                                                                                       <td valign=\"top\" align=\"left\"\r\n"
		+ "                                                                                          name=\"x_tblCell\"\r\n"
		+ "                                                                                          class=\"x_tblCell\"\r\n"
		+ "                                                                                          style=\"padding:10px 20px; font-family:Arial,Helvetica,sans-serif; font-size:14px; font-weight:400; color:rgb(56,56,56); text-align:left; word-break:break-word\">\r\n"
		+ "                                                                                       </td>\r\n"
		+ "                                                                                    </tr>\r\n"
		+ "                                                                                 </tbody>\r\n"
		+ "                                                                              </table>\r\n"
		+ "                                                                           </th>\r\n"
		+ "                                                                        </tr>\r\n"
		+ "                                                                     </tbody>\r\n"
		+ "                                                                  </table>\r\n"
		+ "                                                               </td>\r\n"
		+ "                                                            </tr>\r\n"
		+ "                                                         </tbody>\r\n"
		+ "                                                      </table>\r\n"
		+ "                                                   </div>\r\n"
		+ "                                                   <div id=\"x_dv_12\" class=\"x_blk_wrapper\" style=\"\">\r\n"
		+ "                                                      <table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"\r\n"
		+ "                                                         class=\"x_blk\" name=\"x_blk_text\">\r\n"
		+ "                                                         <tbody>\r\n"
		+ "                                                            <tr>\r\n"
		+ "                                                               <td>\r\n"
		+ "                                                                  <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"\r\n"
		+ "                                                                     width=\"100%\" class=\"x_bmeContainerRow\">\r\n"
		+ "                                                                     <tbody>\r\n"
		+ "                                                                        <tr>\r\n"
		+ "                                                                           <th class=\"x_tdPart\" valign=\"top\"\r\n"
		+ "                                                                              align=\"center\">\r\n"
		+ "                                                                              <table cellspacing=\"0\" cellpadding=\"0\"\r\n"
		+ "                                                                                 border=\"0\" width=\"600\" name=\"x_tblText\"\r\n"
		+ "                                                                                 class=\"x_tblText\" align=\"left\"\r\n"
		+ "                                                                                 style=\"float:left; background-color:transparent\">\r\n"
		+ "                                                                                 <tbody>\r\n"
		+ "                                                                                    <tr>\r\n"
		+ "                                                                                       <td valign=\"top\" align=\"left\"\r\n"
		+ "                                                                                          name=\"x_tblCell\"\r\n"
		+ "                                                                                          class=\"x_tblCell\"\r\n"
		+ "                                                                                          style=\"padding:10px 20px; font-family:Arial,Helvetica,sans-serif; font-size:14px; font-weight:400; color:rgb(56,56,56); text-align:left; word-break:break-word\">\r\n"
		+ "                                                                                          <div><span\r\n"
		+ "                                                                                                style=\"font-family:Helvetica,Arial,sans-serif; font-size:19px; color:#707070; line-height:125%\">{mensagemInicial}</span></div>\r\n"
		+ "                                                                                          <div>&nbsp;</div>\r\n"
		+ "                                                                                       </td>\r\n"
		+ "                                                                                    </tr>\r\n"
		+ "                                                                                 </tbody>\r\n"
		+ "                                                                              </table>\r\n"
		+ "                                                                           </th>\r\n"
		+ "                                                                        </tr>\r\n"
		+ "                                                                     </tbody>\r\n"
		+ "                                                                  </table>\r\n"
		+ "                                                               </td>\r\n"
		+ "                                                            </tr>\r\n"
		+ "                                                         </tbody>\r\n"
		+ "                                                      </table>\r\n"
		+ "                                                   </div>\r\n"
		+ "                                                   <div id=\"x_dv_3\" class=\"x_blk_wrapper\" style=\"\">\r\n"
		+ "                                                      <table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"\r\n"
		+ "                                                         class=\"x_blk\" name=\"x_blk_text\">\r\n"
		+ "                                                         <tbody>\r\n"
		+ "                                                            <tr>\r\n"
		+ "                                                               <td>\r\n"
		+ "                                                                  <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"\r\n"
		+ "                                                                     width=\"100%\" class=\"x_bmeContainerRow\">\r\n"
		+ "                                                                     <tbody>\r\n"
		+ "                                                                        <tr>\r\n"
		+ "                                                                           <th class=\"x_tdPart\" valign=\"top\"\r\n"
		+ "                                                                              align=\"center\">\r\n"
		+ "                                                                              <table cellspacing=\"0\" cellpadding=\"0\"\r\n"
		+ "                                                                                 border=\"0\" width=\"600\" name=\"x_tblText\"\r\n"
		+ "                                                                                 class=\"x_tblText\" align=\"left\"\r\n"
		+ "                                                                                 style=\"float:left; background-color:transparent\">\r\n"
		+ "                                                                                 <tbody>\r\n"
		+ "                                                                                    <tr>\r\n"
		+ "                                                                                       <td valign=\"top\" align=\"left\"\r\n"
		+ "                                                                                          name=\"x_tblCell\"\r\n"
		+ "                                                                                          class=\"x_tblCell\"\r\n"
		+ "                                                                                          style=\"padding:10px 20px; font-family:Arial,Helvetica,sans-serif; font-size:14px; font-weight:400; color:rgb(56,56,56); text-align:left; word-break:break-word\">\r\n"
		+ "                                                                                          <div style=\"line-height:150%\">\r\n"
		+ "                                                                                             <span\r\n"
		+ "                                                                                                style=\"font-size:27px; font-family:Helvetica,Arial,sans-serif\"><span\r\n"
		+ "                                                                                                   style=\"line-height:150%; color:#0bc4a5\">{saudacao}</span></span>\r\n"
		+ "                                                                                          </div>\r\n"
		+ "                                                                                          <div style=\"line-height:150%\">\r\n"
		+ "                                                                                             &nbsp;</div>\r\n"
		+ "                                                                                       </td>\r\n"
		+ "                                                                                    </tr>\r\n"
		+ "                                                                                 </tbody>\r\n"
		+ "                                                                              </table>\r\n"
		+ "                                                                           </th>\r\n"
		+ "                                                                        </tr>\r\n"
		+ "                                                                     </tbody>\r\n"
		+ "                                                                  </table>\r\n"
		+ "                                                               </td>\r\n"
		+ "                                                            </tr>\r\n"
		+ "                                                         </tbody>\r\n"
		+ "                                                      </table>\r\n"
		+ "                                                   </div>\r\n"
		+ "                                                   <div id=\"x_dv_1\" class=\"x_blk_wrapper\" style=\"\">\r\n"
		+ "                                                      <table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"\r\n"
		+ "                                                         class=\"x_blk\" name=\"x_blk_text\">\r\n"
		+ "                                                         <tbody>\r\n"
		+ "                                                            <tr>\r\n"
		+ "                                                               <td>\r\n"
		+ "                                                                  <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"\r\n"
		+ "                                                                     width=\"100%\" class=\"x_bmeContainerRow\">\r\n"
		+ "                                                                     <tbody>\r\n"
		+ "                                                                        <tr>\r\n"
		+ "                                                                           <th class=\"x_tdPart\" valign=\"top\"\r\n"
		+ "                                                                              align=\"center\">\r\n"
		+ "                                                                              <table cellspacing=\"0\" cellpadding=\"0\"\r\n"
		+ "                                                                                 border=\"0\" width=\"600\" name=\"x_tblText\"\r\n"
		+ "                                                                                 class=\"x_tblText\" align=\"left\"\r\n"
		+ "                                                                                 style=\"float:left; background-color:transparent\">\r\n"
		+ "                                                                                 <tbody>\r\n"
		+ "                                                                                    <tr>\r\n"
		+ "                                                                                       <td valign=\"top\" align=\"left\"\r\n"
		+ "                                                                                          name=\"x_tblCell\"\r\n"
		+ "                                                                                          class=\"x_tblCell\"\r\n"
		+ "                                                                                          style=\"padding:10px 20px; font-family:Arial,Helvetica,sans-serif; font-size:14px; font-weight:400; color:rgb(56,56,56); text-align:left; word-break:break-word\">\r\n"
		+ "                                                                                          <div style=\"line-height:150%\">\r\n"
		+ "                                                                                             <div\r\n"
		+ "                                                                                                style=\"text-align:left\">\r\n"
		+ "                                                                                                <span\r\n"
		+ "                                                                                                   style=\"font-size:19px; line-height:150%; font-family:Helvetica,Arial,sans-serif; color:#707070\">Detalhes:</span>\r\n"
		+ "                                                                                             </div>\r\n"
		+ "                                                                                             <div\r\n"
		+ "                                                                                                style=\"text-align:left\">\r\n"
		+ "                                                                                                &nbsp;</div>\r\n"
		+ "                                                                                             <div\r\n"
		+ "                                                                                                style=\"text-align:left\">\r\n"
		+ "                                                                                                <br><span\r\n"
		+ "                                                                                                   style=\"font-size:19px; line-height:150%; font-family:Helvetica,Arial,sans-serif; color:#707070\"><strong>Data\r\n"
		+ "                                                                                                      do\r\n"
		+ "                                                                                                      depósito: </strong>{dataDeposito}</span>\r\n"
		+ "                                                                                                <br><span\r\n"
		+ "                                                                                                   style=\"font-size:19px; line-height:150%; font-family:Helvetica,Arial,sans-serif; color:#707070\"><strong>Local:</strong>\r\n"
		+ "                                                                                                   {nomeCondominio}</span>\r\n"
		+ "                                                                                                <br><span\r\n"
		+ "                                                                                                   style=\"font-size:19px; line-height:150%; font-family:Helvetica,Arial,sans-serif; color:#707070\"><strong>Nome\r\n"
		+ "                                                                                                      do\r\n"
		+ "                                                                                                      box: </strong>{nomeBox}</span>\r\n"
		+ "                                                                                             </div>\r\n"
		+ "                                                                                          </div>\r\n"
		+ "                                                                                       </td>\r\n"
		+ "                                                                                    </tr>\r\n"
		+ "                                                                                 </tbody>\r\n"
		+ "                                                                              </table>\r\n"
		+ "                                                                           </th>\r\n"
		+ "                                                                        </tr>\r\n"
		+ "                                                                     </tbody>\r\n"
		+ "                                                                  </table>\r\n"
		+ "                                                               </td>\r\n"
		+ "                                                            </tr>\r\n"
		+ "                                                         </tbody>\r\n"
		+ "                                                      </table>\r\n"
		+ "                                                   </div>\r\n"
		+ "                                                   <div id=\"x_dv_4\" class=\"x_blk_wrapper\" style=\"\">\r\n"
		+ "                                                      <table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"\r\n"
		+ "                                                         class=\"x_blk\" name=\"x_blk_text\">\r\n"
		+ "                                                         <tbody>\r\n"
		+ "                                                            <tr>\r\n"
		+ "                                                               <td>\r\n"
		+ "                                                                  <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"\r\n"
		+ "                                                                     width=\"100%\" class=\"x_bmeContainerRow\">\r\n"
		+ "                                                                     <tbody>\r\n"
		+ "                                                                        <tr>\r\n"
		+ "                                                                           <th class=\"x_tdPart\" valign=\"top\"\r\n"
		+ "                                                                              align=\"center\">\r\n"
		+ "                                                                              <table cellspacing=\"0\" cellpadding=\"0\"\r\n"
		+ "                                                                                 border=\"0\" width=\"600\" name=\"x_tblText\"\r\n"
		+ "                                                                                 class=\"x_tblText\" align=\"left\"\r\n"
		+ "                                                                                 style=\"float:left; background-color:transparent\">\r\n"
		+ "                                                                                 <tbody>\r\n"
		+ "                                                                                    <tr>\r\n"
		+ "                                                                                       <td valign=\"top\" align=\"left\"\r\n"
		+ "                                                                                          name=\"x_tblCell\"\r\n"
		+ "                                                                                          class=\"x_tblCell\"\r\n"
		+ "                                                                                          style=\"padding:20px; font-family:Arial,Helvetica,sans-serif; font-size:14px; font-weight:400; color:rgb(56,56,56); text-align:left; word-break:break-word\">\r\n"
		+ "                                                                                          <div style=\"line-height:150%\">\r\n"
		+ "                                                                                             <div\r\n"
		+ "                                                                                                style=\"text-align:left\">\r\n"
		+ "                                                                                                <span\r\n"
		+ "                                                                                                   style=\"font-size:19px; line-height:150%; font-family:Helvetica,Arial,sans-serif; color:#707070\">Digite\r\n"
		+ "                                                                                                   o código de\r\n"
		+ "                                                                                                   acesso para\r\n"
		+ "                                                                                                   retirar sua\r\n"
		+ "                                                                                                   encomenda.</span>\r\n"
		+ "                                                                                             </div>\r\n"
		+ "                                                                                             <div\r\n"
		+ "                                                                                                style=\"text-align:center\">\r\n"
		+ "                                                                                                &nbsp;</div>\r\n"
		+ "                                                                                          </div>\r\n"
		+ "                                                                                       </td>\r\n"
		+ "                                                                                    </tr>\r\n"
		+ "                                                                                 </tbody>\r\n"
		+ "                                                                              </table>\r\n"
		+ "                                                                           </th>\r\n"
		+ "                                                                        </tr>\r\n"
		+ "                                                                     </tbody>\r\n"
		+ "                                                                  </table>\r\n"
		+ "                                                               </td>\r\n"
		+ "                                                            </tr>\r\n"
		+ "                                                         </tbody>\r\n"
		+ "                                                      </table>\r\n"
		+ "                                                   </div>\r\n"
		+ "                                                   <div id=\"x_dv_2\" class=\"x_blk_wrapper\" style=\"\">\r\n"
		+ "                                                      <table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"\r\n"
		+ "                                                         class=\"x_blk\" name=\"x_blk_text\">\r\n"
		+ "                                                         <tbody>\r\n"
		+ "                                                            <tr>\r\n"
		+ "                                                               <td>\r\n"
		+ "                                                                  <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"\r\n"
		+ "                                                                     width=\"100%\" class=\"x_bmeContainerRow\">\r\n"
		+ "                                                                     <tbody>\r\n"
		+ "                                                                        <tr>\r\n"
		+ "                                                                           <th class=\"x_tdPart\" valign=\"top\"\r\n"
		+ "                                                                              align=\"center\"\r\n"
		+ "                                                                              style=\"background-color:rgb(239,249,246)\">\r\n"
		+ "                                                                              <table cellspacing=\"0\" cellpadding=\"0\"\r\n"
		+ "                                                                                 border=\"0\" width=\"600\" name=\"x_tblText\"\r\n"
		+ "                                                                                 class=\"x_tblText\" align=\"left\"\r\n"
		+ "                                                                                 style=\"float:left; background-color:rgb(239,249,246)\">\r\n"
		+ "                                                                                 <tbody>\r\n"
		+ "                                                                                    <tr>\r\n"
		+ "                                                                                       <td valign=\"top\" align=\"left\"\r\n"
		+ "                                                                                          name=\"x_tblCell\"\r\n"
		+ "                                                                                          class=\"x_tblCell\"\r\n"
		+ "                                                                                          style=\"padding:20px; font-family:Arial,Helvetica,sans-serif; font-size:14px; font-weight:400; color:rgb(56,56,56); text-align:left; word-break:break-word\">\r\n"
		+ "                                                                                          <div\r\n"
		+ "                                                                                             style=\"line-height:150%; text-align:center\">\r\n"
		+ "                                                                                             <span\r\n"
		+ "                                                                                                style=\"font-size:30px; line-height:150%; font-family:Helvetica,Arial,sans-serif; color:#0bc4a5\">Código:\r\n"
		+ "                                                                                             </span>\r\n"
		+ "                                                                                          </div>\r\n"
		+ "                                                                                          <div\r\n"
		+ "                                                                                             style=\"line-height:150%; text-align:center\">\r\n"
		+ "                                                                                             <span\r\n"
		+ "                                                                                                style=\"font-size:30px; line-height:150%; font-family:Helvetica,Arial,sans-serif; color:#707070\"><strong>{codigoRetirada}</strong></span>\r\n"
		+ "                                                                                          </div>\r\n"
		+ "                                                                                       </td>\r\n"
		+ "                                                                                    </tr>\r\n"
		+ "                                                                                 </tbody>\r\n"
		+ "                                                                              </table>\r\n"
		+ "                                                                           </th>\r\n"
		+ "                                                                        </tr>\r\n"
		+ "                                                                     </tbody>\r\n"
		+ "                                                                  </table>\r\n"
		+ "                                                               </td>\r\n"
		+ "                                                            </tr>\r\n"
		+ "                                                         </tbody>\r\n"
		+ "                                                      </table>\r\n"
		+ "                                                   </div>\r\n"
		+ "												   <div id=\"x_dv_13\" class=\"x_blk_wrapper\" style=\"background-color:rgb(239,249,246)\">\r\n"
		+ "                                                                                <table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" class=\"x_blk\" name=\"x_blk_image\">\r\n"
		+ "                                                                                    <tbody>\r\n"
		+ "                                                                                        <tr>\r\n"
		+ "                                                                                            <td>\r\n"
		+ "                                                                                                <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\">\r\n"
		+ "                                                                                                    <tbody>\r\n"
		+ "                                                                                                        <tr>\r\n"
		+ "                                                                                                            <td align=\"center\" class=\"x_bmeImage\" style=\"border-collapse:collapse; padding-left:20px; padding-right:20px; padding-top:20px; padding-bottom:20px\">\r\n"
		+ "                                                                                                            </td>\r\n"
		+ "                                                                                                                <center><img data-imagetype=\"External\" src=\"data:image/png;base64,{qrCodeBase64}\" width=\"380\" alt=\"\" border=\"0\" class=\"x_keep-custom-width x_mobile-img-large\" style=\"max-width:380px; display:block; border-radius:0px\"></center>\r\n"
		+ "                                                                                                        </tr>\r\n"
		+ "                                                                                                    </tbody>\r\n"
		+ "                                                                                                </table>\r\n"
		+ "                                                                                            </td>\r\n"
		+ "                                                                                        </tr>\r\n"
		+ "                                                                                    </tbody>\r\n"
		+ "                                                                                </table>\r\n"
		+ "																				<br><br>\r\n"
		+ "                                                                            </div>\r\n"
		+ "                                                   <div id=\"x_dv_19\" class=\"x_blk_wrapper\" style=\"\">\r\n"
		+ "                                                      <table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"\r\n"
		+ "                                                         class=\"x_blk\" name=\"x_blk_divider\" style=\"\">\r\n"
		+ "                                                         <tbody>\r\n"
		+ "                                                            <tr>\r\n"
		+ "                                                               <td class=\"x_tblCellMain\" style=\"padding:20px 20px 25px\">\r\n"
		+ "                                                                  <table class=\"x_tblLine\" cellspacing=\"0\"\r\n"
		+ "                                                                     cellpadding=\"0\" border=\"0\" width=\"100%\"\r\n"
		+ "                                                                     style=\"border-top-width:0px; border-top-style:none; min-width:1px\">\r\n"
		+ "                                                                     <tbody>\r\n"
		+ "                                                                        <tr>\r\n"
		+ "                                                                           <td><span></span></td>\r\n"
		+ "                                                                        </tr>\r\n"
		+ "                                                                     </tbody>\r\n"
		+ "                                                                  </table>\r\n"
		+ "                                                               </td>\r\n"
		+ "                                                            </tr>\r\n"
		+ "                                                         </tbody>\r\n"
		+ "                                                      </table>\r\n"
		+ "                                                   </div>\r\n"
		+ "                                                   <div id=\"x_dv_5\" class=\"x_blk_wrapper\" style=\"\">\r\n"
		+ "                                                      <table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"\r\n"
		+ "                                                         class=\"x_blk\" name=\"x_blk_text\">\r\n"
		+ "                                                         <tbody>\r\n"
		+ "                                                            <tr>\r\n"
		+ "                                                               <td>\r\n"
		+ "                                                                  <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"\r\n"
		+ "                                                                     width=\"100%\" class=\"x_bmeContainerRow\">\r\n"
		+ "                                                                     <tbody>\r\n"
		+ "                                                                        <tr>\r\n"
		+ "                                                                           <th class=\"x_tdPart\" valign=\"top\"\r\n"
		+ "                                                                              align=\"center\">\r\n"
		+ "                                                                              <table cellspacing=\"0\" cellpadding=\"0\"\r\n"
		+ "                                                                                 border=\"0\" width=\"600\" name=\"x_tblText\"\r\n"
		+ "                                                                                 class=\"x_tblText\" align=\"left\"\r\n"
		+ "                                                                                 style=\"float:left; background-color:transparent\">\r\n"
		+ "                                                                                 <tbody>\r\n"
		+ "                                                                                    <tr>\r\n"
		+ "                                                                                       <td valign=\"top\" align=\"left\"\r\n"
		+ "                                                                                          name=\"x_tblCell\"\r\n"
		+ "                                                                                          class=\"x_tblCell\"\r\n"
		+ "                                                                                          style=\"padding:10px 20px; font-family:Arial,Helvetica,sans-serif; font-size:14px; font-weight:400; color:rgb(56,56,56); text-align:left; word-break:break-word\">\r\n"
		+ "                                                                                          <div style=\"line-height:125%\">\r\n"
		+ "                                                                                             <span\r\n"
		+ "                                                                                                style=\"font-family:Helvetica,Arial,sans-serif; font-size:17px; line-height:125%; color:#0bc4a5\"><strong><span\r\n"
		+ "                                                                                                      style=\"font-family:Helvetica,Arial,sans-serif; font-size:17px; line-height:125%; color:#0bc4a5\">Para\r\n"
		+ "                                                                                                      retirá-la\r\n"
		+ "                                                                                                      siga as\r\n"
		+ "                                                                                                      instruções\r\n"
		+ "                                                                                                      abaixo:</span></strong></span>\r\n"
		+ "                                                                                             <ol>\r\n"
		+ "                                                                                                <li\r\n"
		+ "                                                                                                   style=\"line-height:125%\">\r\n"
		+ "                                                                                                   <strong><span\r\n"
		+ "                                                                                                         style=\"font-family:Helvetica,Arial,sans-serif; font-size:17px; line-height:125%; color:#707070\">Vá\r\n"
		+ "                                                                                                         até o\r\n"
		+ "                                                                                                         armário\r\n"
		+ "                                                                                                         indicado</span></strong>\r\n"
		+ "                                                                                                </li>\r\n"
		+ "                                                                                                <li\r\n"
		+ "                                                                                                   style=\"line-height:125%\">\r\n"
		+ "                                                                                                   <strong><span\r\n"
		+ "                                                                                                         style=\"font-family:Helvetica,Arial,sans-serif; font-size:17px; line-height:125%; color:#707070\">Clique\r\n"
		+ "                                                                                                         em&nbsp;\r\n"
		+ "                                                                                                         \"Retirar encomenda\"</span></strong>\r\n"
		+ "                                                                                                </li>\r\n"
		+ "                                                                                                <li\r\n"
		+ "                                                                                                   style=\"line-height:125%\">\r\n"
		+ "                                                                                                   <strong><span\r\n"
		+ "                                                                                                         style=\"font-family:Helvetica,Arial,sans-serif; font-size:17px; line-height:125%; color:#707070\">Digite\r\n"
		+ "                                                                                                         o código\r\n"
		+ "                                                                                                         recebido\r\n"
		+ "                                                                                                         nesse\r\n"
		+ "                                                                                                         Email.</span></strong>\r\n"
		+ "                                                                                                </li>\r\n"
		+ "                                                                                             </ol>\r\n"
		+ "                                                                                          </div>\r\n"
		+ "                                                                                       </td>\r\n"
		+ "                                                                                    </tr>\r\n"
		+ "                                                                                 </tbody>\r\n"
		+ "                                                                              </table>\r\n"
		+ "                                                                           </th>\r\n"
		+ "                                                                        </tr>\r\n"
		+ "                                                                     </tbody>\r\n"
		+ "                                                                  </table>\r\n"
		+ "                                                               </td>\r\n"
		+ "                                                            </tr>\r\n"
		+ "                                                         </tbody>\r\n"
		+ "                                                      </table>\r\n"
		+ "                                                   </div>\r\n"
		+ "                                                   <div id=\"x_dv_9\" class=\"x_blk_wrapper\" style=\"\">\r\n"
		+ "                                                      <table width=\"600\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\"\r\n"
		+ "                                                         class=\"x_blk\" name=\"x_blk_text\">\r\n"
		+ "                                                         <tbody>\r\n"
		+ "                                                            <tr>\r\n"
		+ "                                                               <td>\r\n"
		+ "                                                                  <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\"\r\n"
		+ "                                                                     width=\"100%\" class=\"x_bmeContainerRow\">\r\n"
		+ "                                                                     <tbody>\r\n"
		+ "                                                                        <tr>\r\n"
		+ "                                                                           <th class=\"x_tdPart\" valign=\"top\"\r\n"
		+ "                                                                              align=\"center\">\r\n"
		+ "                                                                              <table cellspacing=\"0\" cellpadding=\"0\"\r\n"
		+ "                                                                                 border=\"0\" width=\"600\" name=\"x_tblText\"\r\n"
		+ "                                                                                 class=\"x_tblText\" align=\"left\"\r\n"
		+ "                                                                                 style=\"float:left; background-color:transparent\">\r\n"
		+ "                                                                                 <tbody>\r\n"
		+ "                                                                                    <tr>\r\n"
		+ "                                                                                       <td valign=\"top\" align=\"left\"\r\n"
		+ "                                                                                          name=\"x_tblCell\"\r\n"
		+ "                                                                                          class=\"x_tblCell\"\r\n"
		+ "                                                                                          style=\"padding:10px 20px; font-family:Arial,Helvetica,sans-serif; font-size:14px; font-weight:400; color:rgb(56,56,56); text-align:left; word-break:break-word\">\r\n"
		+ "                                                                                          <div style=\"line-height:150%\">\r\n"
		+ "                                                                                             <div\r\n"
		+ "                                                                                                style=\"text-align:left\">\r\n"
		+ "                                                                                                <span\r\n"
		+ "                                                                                                   style=\"font-size:17px; line-height:150%; font-family:Helvetica,Arial,sans-serif\">Agradecemos\r\n"
		+ "                                                                                                   sua atenção,\r\n"
		+ "                                                                                                   até a próxima\r\n"
		+ "                                                                                                   entrega!</span>\r\n"
		+ "                                                                                             </div>\r\n"
		+ "                                                                                             <div\r\n"
		+ "                                                                                                style=\"text-align:left\">\r\n"
		+ "                                                                                                &nbsp;</div>\r\n"
		+ "                                                                                             <div\r\n"
		+ "                                                                                                style=\"text-align:left\">\r\n"
		+ "                                                                                                <span\r\n"
		+ "                                                                                                   style=\"font-size:17px; line-height:150%; font-family:Helvetica,Arial,sans-serif\"><strong>Abraços,\r\n"
		+ "                                                                                                      <br>Equipe\r\n"
		+ "                                                                                                      Bonabox</strong></span>\r\n"
		+ "                                                                                             </div>\r\n"
		+ "                                                                                             <div\r\n"
		+ "                                                                                                style=\"text-align:left\">\r\n"
		+ "                                                                                                &nbsp;</div>\r\n"
		+ "                                                                                             <div\r\n"
		+ "                                                                                                style=\"text-align:left\">\r\n"
		+ "                                                                                                &nbsp;</div>\r\n"
		+ "                                                                                          </div>\r\n"
		+ "                                                                                       </td>\r\n"
		+ "                                                                                    </tr>\r\n"
		+ "                                                                                 </tbody>\r\n"
		+ "                                                                              </table>\r\n"
		+ "                                                                           </th>\r\n"
		+ "                                                                        </tr>\r\n"
		+ "                                                                     </tbody>\r\n"
		+ "                                                                  </table>\r\n"
		+ "                                                               </td>\r\n"
		+ "                                                            </tr>\r\n"
		+ "                                                         </tbody>\r\n"
		+ "                                                      </table>\r\n"
		+ "                                                   </div>\r\n"
		+ "                                                </td>\r\n"
		+ "                                             </tr>\r\n"
		+ "                                          </tbody>\r\n"
		+ "                                       </table>\r\n"
		+ "                                    </td>\r\n"
		+ "                                 </tr>\r\n"
		+ "                              </tbody>\r\n"
		+ "                           </table>\r\n"
		+ "                        </td>\r\n"
		+ "                     </tr>\r\n"
		+ "                  </tbody>\r\n"
		+ "               </table>\r\n"
		+ "            </td>\r\n"
		+ "         </tr>\r\n"
		+ "      </tbody>\r\n"
		+ "   </table>\r\n"
		+ "</body>\r\n"
		+ "\r\n"
		+ "</html>";

			bodyEmail = bodyEmail.replace("{saudacao}", saudacao);
			bodyEmail = bodyEmail.replace("{nomeTransportadora}", nomeTransportadora);
			bodyEmail = bodyEmail.replace("{dataDeposito}", dataDeposito);
			bodyEmail = bodyEmail.replace("{nomeCondominio}", nomeCondominio);
			bodyEmail = bodyEmail.replace("{nomeBox}", nomeBox);
			bodyEmail = bodyEmail.replace("{codigoRetirada}", codigoRetirada);
			bodyEmail = bodyEmail.replace("{qrCodeBase64}", qrCodeBase64);
			bodyEmail = bodyEmail.replace("{mensagemInicial}", mensagemInicial);
			
            helper.setText(bodyEmail, true);
            helper.setFrom("bonabox_nao_responda@newsafe.com.br");
            
            logger.info("E-mail criado e pronto pra enviar");
           
            emailSender.send(mail);
            logger.info("E-mail enviado para {}", destinatario);
            
            try {
				// ### Temporário
				Notificacao notificacao = new Notificacao(UUID.randomUUID().toString(), "EMAIL", bodyEmail.getBytes(),
						LocalDateTime.now());
				webClientBonabox.build(webClient);
				webClientBonabox.post(notificacao, Notificacao.class, "/notificacao").block();
            }catch (Exception e) {
				// TODO: handle exception
			}
            return true;
        } catch (Exception e) {
        	logger.error("Erro ao tentar enviar e-mail para {} | erro: {}", destinatario, e.getLocalizedMessage() );
        }
		return false;
	}

	@Override
	public boolean enviarLista(Map<String, String> map) throws DataProviderException {
		map.entrySet().stream().forEach(a -> {
			try {
				enviar(a.getValue(), a.getKey());
			} catch (DataProviderException e) {
				e.printStackTrace();
			}
		});
		return true;
	}

	@Override
	public EnviarNotificacaoDataProvider build(DataMDC dataMDC) {
		// TODO Auto-generated method stub
		return null;
	}
}

interface EmailService {
	void sendSimpleMessage(String to, String subject, String text);
}
