server:
    port : 8080
    tomcat:
        max-threads: 100
        max-connections: 100

spring:
    profiles:
        active: ${ENVIRONMENT:dev}
        profiles: dev, prd

integration:
    timeout:
        backend: 10000