package br.com.bonabox.condominio.api.domain.repository.entity;
// Generated 17 de out de 2020 18:06:22 by Hibernate Tools 5.4.18.Final

/**
 * CondominioUnidadesId generated by hbm2java
 */
public class CondominioUnidadesId implements java.io.Serializable {

	private int codigoUnidade;
	private int codigoCondominio;
	private int codigoPessoa;

	public CondominioUnidadesId() {
	}

	public CondominioUnidadesId(int codigoUnidade, int codigoCondominio, int codigoPessoa) {
		this.codigoUnidade = codigoUnidade;
		this.codigoCondominio = codigoCondominio;
		this.codigoPessoa = codigoPessoa;
	}

	public int getCodigoUnidade() {
		return this.codigoUnidade;
	}

	public void setCodigoUnidade(int codigoUnidade) {
		this.codigoUnidade = codigoUnidade;
	}

	public int getCodigoCondominio() {
		return this.codigoCondominio;
	}

	public void setCodigoCondominio(int codigoCondominio) {
		this.codigoCondominio = codigoCondominio;
	}

	public int getCodigoPessoa() {
		return this.codigoPessoa;
	}

	public void setCodigoPessoa(int codigoPessoa) {
		this.codigoPessoa = codigoPessoa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CondominioUnidadesId))
			return false;
		CondominioUnidadesId castOther = (CondominioUnidadesId) other;

		return (this.getCodigoUnidade() == castOther.getCodigoUnidade())
				&& (this.getCodigoCondominio() == castOther.getCodigoCondominio())
				&& (this.getCodigoPessoa() == castOther.getCodigoPessoa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoUnidade();
		result = 37 * result + this.getCodigoCondominio();
		result = 37 * result + this.getCodigoPessoa();
		return result;
	}

}
