package br.com.bonabox.condominio.api.domain.repository.entity;
// Generated 17 de out de 2020 18:06:22 by Hibernate Tools 5.4.18.Final

/**
 * CondominioPessos generated by hbm2java
 */
public class CondominioPessos implements java.io.Serializable {

	private CondominioPessosId id;
	private CondominioEntity condominio;
	private PessoaEntity pessoa;
	private TipoPessoa tipoPessoa;

	public CondominioPessos() {
	}

	public CondominioPessos(CondominioPessosId id, CondominioEntity condominio, PessoaEntity pessoa, TipoPessoa tipoPessoa) {
		this.id = id;
		this.condominio = condominio;
		this.pessoa = pessoa;
		this.tipoPessoa = tipoPessoa;
	}

	public CondominioPessosId getId() {
		return this.id;
	}

	public void setId(CondominioPessosId id) {
		this.id = id;
	}

	public CondominioEntity getCondominio() {
		return this.condominio;
	}

	public void setCondominio(CondominioEntity condominio) {
		this.condominio = condominio;
	}

	public PessoaEntity getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(PessoaEntity pessoa) {
		this.pessoa = pessoa;
	}

	public TipoPessoa getTipoPessoa() {
		return this.tipoPessoa;
	}

	public void setTipoPessoa(TipoPessoa tipoPessoa) {
		this.tipoPessoa = tipoPessoa;
	}

}
