package br.com.bonabox.condominio.api.domain.repository.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pessoa generated by hbm2java
 */
@Entity(name = "CondominioComposicaoEntity")
@Table(name = "condominio_composicao")
public class CondominioComposicaoEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5225839288175193226L;

	@Id
	@Column(name = "condominio_composicao_id", unique = true)
	private Integer condominioComposicaoId;

	@Column(name = "condominio_id", unique = true)
	private Integer condominioId;

	@Column(name = "ala_id")
	private Integer alaId;

	@Column(name = "bloco_id")
	private Integer blocoId;

	@Column(name = "unidade_id")
	private Integer unidadeId;

	public Integer getCondominioComposicaoId() {
		return condominioComposicaoId;
	}

	public void setCondominioComposicaoId(Integer condominioComposicaoId) {
		this.condominioComposicaoId = condominioComposicaoId;
	}

	public Integer getAlaId() {
		return alaId;
	}

	public void setAlaId(Integer alaId) {
		this.alaId = alaId;
	}

	public Integer getBlocoId() {
		return blocoId;
	}

	public void setBlocoId(Integer blocoId) {
		this.blocoId = blocoId;
	}

	public Integer getUnidadeId() {
		return unidadeId;
	}

	public void setUnidadeId(Integer unidadeId) {
		this.unidadeId = unidadeId;
	}

	public Integer getCondominioId() {
		return condominioId;
	}

	public void setCondominioId(Integer condominioId) {
		this.condominioId = condominioId;
	}

}
