package br.com.bonabox.condominio.api.domain.repository.entity;
// Generated 17 de out de 2020 18:06:22 by Hibernate Tools 5.4.18.Final

/**
 * CondominioPessosId generated by hbm2java
 */
public class CondominioPessosId implements java.io.Serializable {

	private int codigoCondominio;
	private int codigoPessoa;
	private int codigoTipoPessoa;

	public CondominioPessosId() {
	}

	public CondominioPessosId(int codigoCondominio, int codigoPessoa, int codigoTipoPessoa) {
		this.codigoCondominio = codigoCondominio;
		this.codigoPessoa = codigoPessoa;
		this.codigoTipoPessoa = codigoTipoPessoa;
	}

	public int getCodigoCondominio() {
		return this.codigoCondominio;
	}

	public void setCodigoCondominio(int codigoCondominio) {
		this.codigoCondominio = codigoCondominio;
	}

	public int getCodigoPessoa() {
		return this.codigoPessoa;
	}

	public void setCodigoPessoa(int codigoPessoa) {
		this.codigoPessoa = codigoPessoa;
	}

	public int getCodigoTipoPessoa() {
		return this.codigoTipoPessoa;
	}

	public void setCodigoTipoPessoa(int codigoTipoPessoa) {
		this.codigoTipoPessoa = codigoTipoPessoa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CondominioPessosId))
			return false;
		CondominioPessosId castOther = (CondominioPessosId) other;

		return (this.getCodigoCondominio() == castOther.getCodigoCondominio())
				&& (this.getCodigoPessoa() == castOther.getCodigoPessoa())
				&& (this.getCodigoTipoPessoa() == castOther.getCodigoTipoPessoa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoCondominio();
		result = 37 * result + this.getCodigoPessoa();
		result = 37 * result + this.getCodigoTipoPessoa();
		return result;
	}

}
