package br.com.bonabox.condominio.api.domain.repository.entity;
// Generated 17 de out de 2020 18:06:22 by Hibernate Tools 5.4.18.Final

/**
 * CondominioEnderecos generated by hbm2java
 */
public class CondominioEnderecos2 implements java.io.Serializable {

	private CondominioEnderecosId id;
	private CondominioEntity condominio;

	public CondominioEnderecos2() {
	}

	public CondominioEnderecos2(CondominioEnderecosId id, CondominioEntity condominio) {
		this.id = id;
		this.condominio = condominio;
	}

	public CondominioEnderecosId getId() {
		return this.id;
	}

	public void setId(CondominioEnderecosId id) {
		this.id = id;
	}

	public CondominioEntity getCondominio() {
		return this.condominio;
	}

	public void setCondominio(CondominioEntity condominio) {
		this.condominio = condominio;
	}

}
