package br.com.bonabox.condominio.api.domain.repository.entity;
// Generated 17 de out de 2020 18:06:22 by Hibernate Tools 5.4.18.Final

/**
 * CondominioEnderecosId generated by hbm2java
 */
public class CondominioEnderecosId implements java.io.Serializable {

	private int codigoCondominio;
	private int cep;
	private String logradouro;
	private String complemento;
	private String bairro;
	private String cidade;
	private String uf;

	public CondominioEnderecosId() {
	}

	public CondominioEnderecosId(int codigoCondominio, int cep) {
		this.codigoCondominio = codigoCondominio;
		this.cep = cep;
	}

	public CondominioEnderecosId(int codigoCondominio, int cep, String logradouro, String complemento, String bairro,
			String cidade, String uf) {
		this.codigoCondominio = codigoCondominio;
		this.cep = cep;
		this.logradouro = logradouro;
		this.complemento = complemento;
		this.bairro = bairro;
		this.cidade = cidade;
		this.uf = uf;
	}

	public int getCodigoCondominio() {
		return this.codigoCondominio;
	}

	public void setCodigoCondominio(int codigoCondominio) {
		this.codigoCondominio = codigoCondominio;
	}

	public int getCep() {
		return this.cep;
	}

	public void setCep(int cep) {
		this.cep = cep;
	}

	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CondominioEnderecosId))
			return false;
		CondominioEnderecosId castOther = (CondominioEnderecosId) other;

		return (this.getCodigoCondominio() == castOther.getCodigoCondominio()) && (this.getCep() == castOther.getCep())
				&& ((this.getLogradouro() == castOther.getLogradouro()) || (this.getLogradouro() != null
						&& castOther.getLogradouro() != null && this.getLogradouro().equals(castOther.getLogradouro())))
				&& ((this.getComplemento() == castOther.getComplemento())
						|| (this.getComplemento() != null && castOther.getComplemento() != null
								&& this.getComplemento().equals(castOther.getComplemento())))
				&& ((this.getBairro() == castOther.getBairro()) || (this.getBairro() != null
						&& castOther.getBairro() != null && this.getBairro().equals(castOther.getBairro())))
				&& ((this.getCidade() == castOther.getCidade()) || (this.getCidade() != null
						&& castOther.getCidade() != null && this.getCidade().equals(castOther.getCidade())))
				&& ((this.getUf() == castOther.getUf()) || (this.getUf() != null && castOther.getUf() != null
						&& this.getUf().equals(castOther.getUf())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoCondominio();
		result = 37 * result + this.getCep();
		result = 37 * result + (getLogradouro() == null ? 0 : this.getLogradouro().hashCode());
		result = 37 * result + (getComplemento() == null ? 0 : this.getComplemento().hashCode());
		result = 37 * result + (getBairro() == null ? 0 : this.getBairro().hashCode());
		result = 37 * result + (getCidade() == null ? 0 : this.getCidade().hashCode());
		result = 37 * result + (getUf() == null ? 0 : this.getUf().hashCode());
		return result;
	}

}
