package br.com.bonabox.condominio.api.domain.repository.entity;
// Generated 17 de out de 2020 18:06:22 by Hibernate Tools 5.4.18.Final

/**
 * CondominioUnidades generated by hbm2java
 */
public class CondominioUnidades implements java.io.Serializable {

	private CondominioUnidadesId id;
	private CondominioEntity condominio;
	private PessoaEntity pessoa;
	private Unidade unidade;

	public CondominioUnidades() {
	}

	public CondominioUnidades(CondominioUnidadesId id, CondominioEntity condominio, PessoaEntity pessoa, Unidade unidade) {
		this.id = id;
		this.condominio = condominio;
		this.pessoa = pessoa;
		this.unidade = unidade;
	}

	public CondominioUnidadesId getId() {
		return this.id;
	}

	public void setId(CondominioUnidadesId id) {
		this.id = id;
	}

	public CondominioEntity getCondominio() {
		return this.condominio;
	}

	public void setCondominio(CondominioEntity condominio) {
		this.condominio = condominio;
	}

	public PessoaEntity getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(PessoaEntity pessoa) {
		this.pessoa = pessoa;
	}

	public Unidade getUnidade() {
		return this.unidade;
	}

	public void setUnidade(Unidade unidade) {
		this.unidade = unidade;
	}

}
