package br.com.bonabox.condominio.api.domain.repository.entity;
// Generated 17 de out de 2020 18:06:22 by Hibernate Tools 5.4.18.Final

/**
 * CondominioAmbientesId generated by hbm2java
 */
public class CondominioAmbientesId implements java.io.Serializable {

	private int codigoCondominio;
	private int codigoAmbiente;
	private int capacidade;
	private Integer codigoResponsavel;

	public CondominioAmbientesId() {
	}

	public CondominioAmbientesId(int codigoCondominio, int codigoAmbiente, int capacidade) {
		this.codigoCondominio = codigoCondominio;
		this.codigoAmbiente = codigoAmbiente;
		this.capacidade = capacidade;
	}

	public CondominioAmbientesId(int codigoCondominio, int codigoAmbiente, int capacidade, Integer codigoResponsavel) {
		this.codigoCondominio = codigoCondominio;
		this.codigoAmbiente = codigoAmbiente;
		this.capacidade = capacidade;
		this.codigoResponsavel = codigoResponsavel;
	}

	public int getCodigoCondominio() {
		return this.codigoCondominio;
	}

	public void setCodigoCondominio(int codigoCondominio) {
		this.codigoCondominio = codigoCondominio;
	}

	public int getCodigoAmbiente() {
		return this.codigoAmbiente;
	}

	public void setCodigoAmbiente(int codigoAmbiente) {
		this.codigoAmbiente = codigoAmbiente;
	}

	public int getCapacidade() {
		return this.capacidade;
	}

	public void setCapacidade(int capacidade) {
		this.capacidade = capacidade;
	}

	public Integer getCodigoResponsavel() {
		return this.codigoResponsavel;
	}

	public void setCodigoResponsavel(Integer codigoResponsavel) {
		this.codigoResponsavel = codigoResponsavel;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CondominioAmbientesId))
			return false;
		CondominioAmbientesId castOther = (CondominioAmbientesId) other;

		return (this.getCodigoCondominio() == castOther.getCodigoCondominio())
				&& (this.getCodigoAmbiente() == castOther.getCodigoAmbiente())
				&& (this.getCapacidade() == castOther.getCapacidade())
				&& ((this.getCodigoResponsavel() == castOther.getCodigoResponsavel())
						|| (this.getCodigoResponsavel() != null && castOther.getCodigoResponsavel() != null
								&& this.getCodigoResponsavel().equals(castOther.getCodigoResponsavel())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoCondominio();
		result = 37 * result + this.getCodigoAmbiente();
		result = 37 * result + this.getCapacidade();
		result = 37 * result + (getCodigoResponsavel() == null ? 0 : this.getCodigoResponsavel().hashCode());
		return result;
	}

}
