package br.com.bonabox.condominio.api.domain.repository.entity;
// Generated 17 de out de 2020 18:06:22 by Hibernate Tools 5.4.18.Final

/**
 * CondominioAmbientes generated by hbm2java
 */
public class CondominioAmbientes implements java.io.Serializable {

	private CondominioAmbientesId id;
	private AmbienteItem ambienteItem;
	private CondominioEntity condominio;
	private PessoaEntity pessoa;

	public CondominioAmbientes() {
	}

	public CondominioAmbientes(CondominioAmbientesId id, AmbienteItem ambienteItem, CondominioEntity condominio) {
		this.id = id;
		this.ambienteItem = ambienteItem;
		this.condominio = condominio;
	}

	public CondominioAmbientes(CondominioAmbientesId id, AmbienteItem ambienteItem, CondominioEntity condominio,
			PessoaEntity pessoa) {
		this.id = id;
		this.ambienteItem = ambienteItem;
		this.condominio = condominio;
		this.pessoa = pessoa;
	}

	public CondominioAmbientesId getId() {
		return this.id;
	}

	public void setId(CondominioAmbientesId id) {
		this.id = id;
	}

	public AmbienteItem getAmbienteItem() {
		return this.ambienteItem;
	}

	public void setAmbienteItem(AmbienteItem ambienteItem) {
		this.ambienteItem = ambienteItem;
	}

	public CondominioEntity getCondominio() {
		return this.condominio;
	}

	public void setCondominio(CondominioEntity condominio) {
		this.condominio = condominio;
	}

	public PessoaEntity getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(PessoaEntity pessoa) {
		this.pessoa = pessoa;
	}

}
