package br.com.bonabox.condominio.api.domain.repository.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pessoa generated by hbm2java
 */
@Entity(name = "PessoaEntity")
@Table(name = "pessoa")
public class PessoaEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5225839288175193226L;

	@Id
	@Column(name = "pessoa_id", unique = true)
	private Integer pessoaId;

	@Column(name = "nome")
	private String nome;

	@Column(name = "numero_celular")
	private String numeroCelular;

	@Column(name = "email")
	private String email;

	@Column(name = "eh_principal")
	private boolean ehPrincipal;

	public PessoaEntity() {
	}

	public boolean isEhPrincipal() {
		return ehPrincipal;
	}

	public void setEhPrincipal(boolean ehPrincipal) {
		this.ehPrincipal = ehPrincipal;
	}

	public Integer getPessoaId() {
		return pessoaId;
	}

	public void setPessoaId(Integer pessoaId) {
		this.pessoaId = pessoaId;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getNumeroCelular() {
		return numeroCelular;
	}

	public void setNumeroCelular(String numeroCelular) {
		this.numeroCelular = numeroCelular;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
