package br.com.bonabox.condominio.api.domain.repository.entity;
// Generated 17 de out de 2020 18:06:22 by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Unidade generated by hbm2java
 */
public class Unidade implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4946455990565491022L;
	private int codigo;
	private String identificacaoBloco;
	private Integer piso;
	private Integer numeroApartamento;
	private String identificacaoApartamento;
	private Set condominioUnidadeses = new HashSet(0);

	public Unidade() {
	}

	public Unidade(int codigo) {
		this.codigo = codigo;
	}

	public Unidade(int codigo, String identificacaoBloco, Integer piso, Integer numeroApartamento,
			String identificacaoApartamento, Set condominioUnidadeses) {
		this.codigo = codigo;
		this.identificacaoBloco = identificacaoBloco;
		this.piso = piso;
		this.numeroApartamento = numeroApartamento;
		this.identificacaoApartamento = identificacaoApartamento;
		this.condominioUnidadeses = condominioUnidadeses;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getIdentificacaoBloco() {
		return this.identificacaoBloco;
	}

	public void setIdentificacaoBloco(String identificacaoBloco) {
		this.identificacaoBloco = identificacaoBloco;
	}

	public Integer getPiso() {
		return this.piso;
	}

	public void setPiso(Integer piso) {
		this.piso = piso;
	}

	public Integer getNumeroApartamento() {
		return this.numeroApartamento;
	}

	public void setNumeroApartamento(Integer numeroApartamento) {
		this.numeroApartamento = numeroApartamento;
	}

	public String getIdentificacaoApartamento() {
		return this.identificacaoApartamento;
	}

	public void setIdentificacaoApartamento(String identificacaoApartamento) {
		this.identificacaoApartamento = identificacaoApartamento;
	}

	public Set getCondominioUnidadeses() {
		return this.condominioUnidadeses;
	}

	public void setCondominioUnidadeses(Set condominioUnidadeses) {
		this.condominioUnidadeses = condominioUnidadeses;
	}

}
