package br.com.bonabox.condominio.api.domain.repository.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pessoa generated by hbm2java
 */
@Entity(name = "UnidadeEntity")
@Table(name = "unidade")
public class UnidadeEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5970023287638042681L;

	@Id
	@Column(name = "unidade_id", unique = true)
	private Integer unidadeId;

	@Column(name = "piso")
	private Integer piso;

	@Column(name = "numero_unidade")
	private Integer numeroUnidade;

	@Column(name = "label_unidade")
	private String labelUnidade;

	public Integer getUnidadeId() {
		return unidadeId;
	}

	public void setUnidadeId(Integer unidadeId) {
		this.unidadeId = unidadeId;
	}

	public Integer getPiso() {
		return piso;
	}

	public void setPiso(Integer piso) {
		this.piso = piso;
	}

	public Integer getNumeroUnidade() {
		return numeroUnidade;
	}

	public void setNumeroUnidade(Integer numeroUnidade) {
		this.numeroUnidade = numeroUnidade;
	}

	public String getLabelUnidade() {
		return labelUnidade;
	}

	public void setLabelUnidade(String labelUnidade) {
		this.labelUnidade = labelUnidade;
	}

}
