spring:
  profiles: dev
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: "jdbc:mysql://database-commons.cgj8xeods5uo.us-east-2.rds.amazonaws.com:3306/db_box?serverTimezone=UTC"
    username: "admin"
    password: "jaE7Q5fpnbv01g5R3S"

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss:SSS,SSSXXX, UTC-3} %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    br.com.santander: DEBUG

bonabox-interno:
  server: "localhost:8081/interno-bonabox/api/v1"