package br.com.bonabox.box.api.domain.entity;
// Generated 17 de out de 2020 18:05:14 by Hibernate Tools 5.4.18.Final

import java.util.Date;

/**
 * BoxDeviceId generated by hbm2java
 */
public class BoxDeviceId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3569667006883114194L;
	private int codigoBox;
	private int codigoDevice;
	private byte ativo;
	private Date dataCadastro;
	private Integer codigoUserCadastro;
	private Date dataAtualizacao;
	private Integer codigoUserAtualizacao;

	public BoxDeviceId() {
	}

	public BoxDeviceId(int codigoBox, int codigoDevice, byte ativo, Date dataCadastro) {
		this.codigoBox = codigoBox;
		this.codigoDevice = codigoDevice;
		this.ativo = ativo;
		this.dataCadastro = dataCadastro;
	}

	public BoxDeviceId(int codigoBox, int codigoDevice, byte ativo, Date dataCadastro, Integer codigoUserCadastro,
			Date dataAtualizacao, Integer codigoUserAtualizacao) {
		this.codigoBox = codigoBox;
		this.codigoDevice = codigoDevice;
		this.ativo = ativo;
		this.dataCadastro = dataCadastro;
		this.codigoUserCadastro = codigoUserCadastro;
		this.dataAtualizacao = dataAtualizacao;
		this.codigoUserAtualizacao = codigoUserAtualizacao;
	}

	public int getCodigoBox() {
		return this.codigoBox;
	}

	public void setCodigoBox(int codigoBox) {
		this.codigoBox = codigoBox;
	}

	public int getCodigoDevice() {
		return this.codigoDevice;
	}

	public void setCodigoDevice(int codigoDevice) {
		this.codigoDevice = codigoDevice;
	}

	public byte getAtivo() {
		return this.ativo;
	}

	public void setAtivo(byte ativo) {
		this.ativo = ativo;
	}

	public Date getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	public Integer getCodigoUserCadastro() {
		return this.codigoUserCadastro;
	}

	public void setCodigoUserCadastro(Integer codigoUserCadastro) {
		this.codigoUserCadastro = codigoUserCadastro;
	}

	public Date getDataAtualizacao() {
		return this.dataAtualizacao;
	}

	public void setDataAtualizacao(Date dataAtualizacao) {
		this.dataAtualizacao = dataAtualizacao;
	}

	public Integer getCodigoUserAtualizacao() {
		return this.codigoUserAtualizacao;
	}

	public void setCodigoUserAtualizacao(Integer codigoUserAtualizacao) {
		this.codigoUserAtualizacao = codigoUserAtualizacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BoxDeviceId))
			return false;
		BoxDeviceId castOther = (BoxDeviceId) other;

		return (this.getCodigoBox() == castOther.getCodigoBox())
				&& (this.getCodigoDevice() == castOther.getCodigoDevice()) && (this.getAtivo() == castOther.getAtivo())
				&& ((this.getDataCadastro() == castOther.getDataCadastro())
						|| (this.getDataCadastro() != null && castOther.getDataCadastro() != null
								&& this.getDataCadastro().equals(castOther.getDataCadastro())))
				&& ((this.getCodigoUserCadastro() == castOther.getCodigoUserCadastro())
						|| (this.getCodigoUserCadastro() != null && castOther.getCodigoUserCadastro() != null
								&& this.getCodigoUserCadastro().equals(castOther.getCodigoUserCadastro())))
				&& ((this.getDataAtualizacao() == castOther.getDataAtualizacao())
						|| (this.getDataAtualizacao() != null && castOther.getDataAtualizacao() != null
								&& this.getDataAtualizacao().equals(castOther.getDataAtualizacao())))
				&& ((this.getCodigoUserAtualizacao() == castOther.getCodigoUserAtualizacao())
						|| (this.getCodigoUserAtualizacao() != null && castOther.getCodigoUserAtualizacao() != null
								&& this.getCodigoUserAtualizacao().equals(castOther.getCodigoUserAtualizacao())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoBox();
		result = 37 * result + this.getCodigoDevice();
		result = 37 * result + this.getAtivo();
		result = 37 * result + (getDataCadastro() == null ? 0 : this.getDataCadastro().hashCode());
		result = 37 * result + (getCodigoUserCadastro() == null ? 0 : this.getCodigoUserCadastro().hashCode());
		result = 37 * result + (getDataAtualizacao() == null ? 0 : this.getDataAtualizacao().hashCode());
		result = 37 * result + (getCodigoUserAtualizacao() == null ? 0 : this.getCodigoUserAtualizacao().hashCode());
		return result;
	}

}
