package br.com.bonabox.box.api.domain.entity;
// Generated 17 de out de 2020 18:05:14 by Hibernate Tools 5.4.18.Final

/**
 * BoxDevice generated by hbm2java
 */
public class BoxDevice implements java.io.Serializable {

	private static final long serialVersionUID = -1276963144767273719L;
	private BoxDeviceId id;
	private BoxEntity box;
	private Device device;

	public BoxDevice() {
	}

	public BoxDevice(BoxDeviceId id, BoxEntity box, Device device) {
		this.id = id;
		this.box = box;
		this.device = device;
	}

	public BoxDeviceId getId() {
		return this.id;
	}

	public void setId(BoxDeviceId id) {
		this.id = id;
	}

	public BoxEntity getBox() {
		return this.box;
	}

	public void setBox(BoxEntity box) {
		this.box = box;
	}

	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

}
