package br.com.bonabox.box.api.domain.entity;
// Generated 17 de out de 2020 18:05:14 by Hibernate Tools 5.4.18.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

/**
 * Box generated by hbm2java
 */
@Entity(name = "BoxEntity")
@Table(name = "box")
public class BoxEntity implements java.io.Serializable {

	private static final long serialVersionUID = -6472477933011820235L;

	@Id
	@Column(name = "box_id", unique = true)
	private int boxId;

	@Column(name = "numero_serial")
	private String numeroSerial;

	@Column(name = "data_hora_cadastro")
	private Date dataCadastro;

	@Column(name = "codigo_user_cadastro")
	private int codigoUserCadastro;

	@Column(name = "data_hora_atualizacao")
	private Date dataAtualizacao;

	@Column(name = "codigo_user_atualizacao")
	private int codigoUserAtualizacao;

	@Column(name = "data_fabricacao")
	private Date dataFabricacao;

	@Column(name = "tipo")
	private String tipo;

	@Column(name = "owner")
	private int owner;

	@Column(name = "nome")
	private String nome;

	public BoxEntity() {
	}

	public BoxEntity(int boxId, String numeroSerial, Date dataCadastro, int codigoUserCadastro, Date dataAtualizacao,
			int codigoUserAtualizacao, Date dataFabricacao, String tipo, int owner, String nome) {
		super();
		this.boxId = boxId;
		this.numeroSerial = numeroSerial;
		this.dataCadastro = dataCadastro;
		this.codigoUserCadastro = codigoUserCadastro;
		this.dataAtualizacao = dataAtualizacao;
		this.codigoUserAtualizacao = codigoUserAtualizacao;
		this.dataFabricacao = dataFabricacao;
		this.tipo = tipo;
		this.owner = owner;
		this.nome = nome;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public int getBoxId() {
		return boxId;
	}

	public void setBoxId(int boxId) {
		this.boxId = boxId;
	}

	public String getNumeroSerial() {
		return numeroSerial;
	}

	public void setNumeroSerial(String numeroSerial) {
		this.numeroSerial = numeroSerial;
	}

	public Date getDataCadastro() {
		return dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	public int getCodigoUserCadastro() {
		return codigoUserCadastro;
	}

	public void setCodigoUserCadastro(int codigoUserCadastro) {
		this.codigoUserCadastro = codigoUserCadastro;
	}

	public Date getDataAtualizacao() {
		return dataAtualizacao;
	}

	public void setDataAtualizacao(Date dataAtualizacao) {
		this.dataAtualizacao = dataAtualizacao;
	}

	public int getCodigoUserAtualizacao() {
		return codigoUserAtualizacao;
	}

	public void setCodigoUserAtualizacao(int codigoUserAtualizacao) {
		this.codigoUserAtualizacao = codigoUserAtualizacao;
	}

	public Date getDataFabricacao() {
		return dataFabricacao;
	}

	public void setDataFabricacao(Date dataFabricacao) {
		this.dataFabricacao = dataFabricacao;
	}

	public String getTipo() {
		return tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public int getOwner() {
		return owner;
	}

	public void setOwner(int owner) {
		this.owner = owner;
	}

}
