package br.com.bonabox.box.api.domain.entity;
// Generated 17 de out de 2020 18:05:14 by Hibernate Tools 5.4.18.Final

/**
 * BoxInstall generated by hbm2java
 */
public class BoxInstall implements java.io.Serializable {

	private static final long serialVersionUID = 7904227039737558807L;
	private int codigoBox;
	private BoxEntity box;
	private EmpresaResponsavel empresaResponsavel;
	private int codigoCondominio;
	private String localizacao;
	private String jsonInfo;
	private String descricao;
	private Byte ativo;
	private String tipoRede;
	private String nomeRede;

	public BoxInstall() {
	}

	public BoxInstall(BoxEntity box, EmpresaResponsavel empresaResponsavel, int codigoCondominio, String localizacao) {
		this.box = box;
		this.empresaResponsavel = empresaResponsavel;
		this.codigoCondominio = codigoCondominio;
		this.localizacao = localizacao;
	}

	public BoxInstall(BoxEntity box, EmpresaResponsavel empresaResponsavel, int codigoCondominio, String localizacao,
			String jsonInfo, String descricao, Byte ativo, String tipoRede, String nomeRede) {
		this.box = box;
		this.empresaResponsavel = empresaResponsavel;
		this.codigoCondominio = codigoCondominio;
		this.localizacao = localizacao;
		this.jsonInfo = jsonInfo;
		this.descricao = descricao;
		this.ativo = ativo;
		this.tipoRede = tipoRede;
		this.nomeRede = nomeRede;
	}

	public int getCodigoBox() {
		return this.codigoBox;
	}

	public void setCodigoBox(int codigoBox) {
		this.codigoBox = codigoBox;
	}

	public BoxEntity getBox() {
		return this.box;
	}

	public void setBox(BoxEntity box) {
		this.box = box;
	}

	public EmpresaResponsavel getEmpresaResponsavel() {
		return this.empresaResponsavel;
	}

	public void setEmpresaResponsavel(EmpresaResponsavel empresaResponsavel) {
		this.empresaResponsavel = empresaResponsavel;
	}

	public int getCodigoCondominio() {
		return this.codigoCondominio;
	}

	public void setCodigoCondominio(int codigoCondominio) {
		this.codigoCondominio = codigoCondominio;
	}

	public String getLocalizacao() {
		return this.localizacao;
	}

	public void setLocalizacao(String localizacao) {
		this.localizacao = localizacao;
	}

	public String getJsonInfo() {
		return this.jsonInfo;
	}

	public void setJsonInfo(String jsonInfo) {
		this.jsonInfo = jsonInfo;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Byte getAtivo() {
		return this.ativo;
	}

	public void setAtivo(Byte ativo) {
		this.ativo = ativo;
	}

	public String getTipoRede() {
		return this.tipoRede;
	}

	public void setTipoRede(String tipoRede) {
		this.tipoRede = tipoRede;
	}

	public String getNomeRede() {
		return this.nomeRede;
	}

	public void setNomeRede(String nomeRede) {
		this.nomeRede = nomeRede;
	}

}
