package br.com.bonabox.box.api.domain.entity;
// Generated 17 de out de 2020 18:05:14 by Hibernate Tools 5.4.18.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Device generated by hbm2java
 */
public class Device implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1530316616831828048L;
	private int codigo;
	private FabricanteEntity fabricante;
	private String numeroSerial;
	private String nome;
	private int tipo;
	private String modelo;
	private long valor;
	private Date dataCompra;
	private Date dataCadastro;
	private int codigoUserCadastro;
	private Date dataAtualizacao;
	private int codigoUserAtualizacao;
	private byte ativo;
	private Set boxDevices = new HashSet(0);

	public Device() {
	}

	public Device(int codigo, FabricanteEntity fabricante, String numeroSerial, String nome, int tipo, String modelo,
                  long valor, Date dataCompra, Date dataCadastro, int codigoUserCadastro, Date dataAtualizacao,
                  int codigoUserAtualizacao, byte ativo) {
		this.codigo = codigo;
		this.fabricante = fabricante;
		this.numeroSerial = numeroSerial;
		this.nome = nome;
		this.tipo = tipo;
		this.modelo = modelo;
		this.valor = valor;
		this.dataCompra = dataCompra;
		this.dataCadastro = dataCadastro;
		this.codigoUserCadastro = codigoUserCadastro;
		this.dataAtualizacao = dataAtualizacao;
		this.codigoUserAtualizacao = codigoUserAtualizacao;
		this.ativo = ativo;
	}

	public Device(int codigo, FabricanteEntity fabricante, String numeroSerial, String nome, int tipo, String modelo,
                  long valor, Date dataCompra, Date dataCadastro, int codigoUserCadastro, Date dataAtualizacao,
                  int codigoUserAtualizacao, byte ativo, Set boxDevices) {
		this.codigo = codigo;
		this.fabricante = fabricante;
		this.numeroSerial = numeroSerial;
		this.nome = nome;
		this.tipo = tipo;
		this.modelo = modelo;
		this.valor = valor;
		this.dataCompra = dataCompra;
		this.dataCadastro = dataCadastro;
		this.codigoUserCadastro = codigoUserCadastro;
		this.dataAtualizacao = dataAtualizacao;
		this.codigoUserAtualizacao = codigoUserAtualizacao;
		this.ativo = ativo;
		this.boxDevices = boxDevices;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public FabricanteEntity getFabricante() {
		return this.fabricante;
	}

	public void setFabricante(FabricanteEntity fabricante) {
		this.fabricante = fabricante;
	}

	public String getNumeroSerial() {
		return this.numeroSerial;
	}

	public void setNumeroSerial(String numeroSerial) {
		this.numeroSerial = numeroSerial;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public int getTipo() {
		return this.tipo;
	}

	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public long getValor() {
		return this.valor;
	}

	public void setValor(long valor) {
		this.valor = valor;
	}

	public Date getDataCompra() {
		return this.dataCompra;
	}

	public void setDataCompra(Date dataCompra) {
		this.dataCompra = dataCompra;
	}

	public Date getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	public int getCodigoUserCadastro() {
		return this.codigoUserCadastro;
	}

	public void setCodigoUserCadastro(int codigoUserCadastro) {
		this.codigoUserCadastro = codigoUserCadastro;
	}

	public Date getDataAtualizacao() {
		return this.dataAtualizacao;
	}

	public void setDataAtualizacao(Date dataAtualizacao) {
		this.dataAtualizacao = dataAtualizacao;
	}

	public int getCodigoUserAtualizacao() {
		return this.codigoUserAtualizacao;
	}

	public void setCodigoUserAtualizacao(int codigoUserAtualizacao) {
		this.codigoUserAtualizacao = codigoUserAtualizacao;
	}

	public byte getAtivo() {
		return this.ativo;
	}

	public void setAtivo(byte ativo) {
		this.ativo = ativo;
	}

	public Set getBoxDevices() {
		return this.boxDevices;
	}

	public void setBoxDevices(Set boxDevices) {
		this.boxDevices = boxDevices;
	}

}
