package br.com.bonabox.box.api.domain.entity;
// Generated 17 de out de 2020 18:05:14 by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EmpresaResponsavel generated by hbm2java
 */
public class EmpresaResponsavel implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8704440615119227652L;
	private int codigo;
	private String nome;
	private String pessoaRepresentante;
	private String contato;
	private String cnpj;
	private Set boxInstalls = new HashSet(0);

	public EmpresaResponsavel() {
	}

	public EmpresaResponsavel(int codigo) {
		this.codigo = codigo;
	}

	public EmpresaResponsavel(int codigo, String nome, String pessoaRepresentante, String contato, String cnpj,
			Set boxInstalls) {
		this.codigo = codigo;
		this.nome = nome;
		this.pessoaRepresentante = pessoaRepresentante;
		this.contato = contato;
		this.cnpj = cnpj;
		this.boxInstalls = boxInstalls;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getPessoaRepresentante() {
		return this.pessoaRepresentante;
	}

	public void setPessoaRepresentante(String pessoaRepresentante) {
		this.pessoaRepresentante = pessoaRepresentante;
	}

	public String getContato() {
		return this.contato;
	}

	public void setContato(String contato) {
		this.contato = contato;
	}

	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	public Set getBoxInstalls() {
		return this.boxInstalls;
	}

	public void setBoxInstalls(Set boxInstalls) {
		this.boxInstalls = boxInstalls;
	}

}
