package br.com.bonabox.box.api.domain.entity;
// Generated 17 de out de 2020 18:05:14 by Hibernate Tools 5.4.18.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Modelo generated by hbm2java
 */
public class Modelo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3982023498259510945L;
	private int codigo;
	private String nome;
	private String cores;
	private Long largura;
	private Long altura;
	private Long profundidade;
	private Long comprimento;
	private Set boxes = new HashSet(0);

	public Modelo() {
	}

	public Modelo(int codigo) {
		this.codigo = codigo;
	}

	public Modelo(int codigo, String nome, String cores, Long largura, Long altura, Long profundidade, Long comprimento,
			Set boxes) {
		this.codigo = codigo;
		this.nome = nome;
		this.cores = cores;
		this.largura = largura;
		this.altura = altura;
		this.profundidade = profundidade;
		this.comprimento = comprimento;
		this.boxes = boxes;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCores() {
		return this.cores;
	}

	public void setCores(String cores) {
		this.cores = cores;
	}

	public Long getLargura() {
		return this.largura;
	}

	public void setLargura(Long largura) {
		this.largura = largura;
	}

	public Long getAltura() {
		return this.altura;
	}

	public void setAltura(Long altura) {
		this.altura = altura;
	}

	public Long getProfundidade() {
		return this.profundidade;
	}

	public void setProfundidade(Long profundidade) {
		this.profundidade = profundidade;
	}

	public Long getComprimento() {
		return this.comprimento;
	}

	public void setComprimento(Long comprimento) {
		this.comprimento = comprimento;
	}

	public Set getBoxes() {
		return this.boxes;
	}

	public void setBoxes(Set boxes) {
		this.boxes = boxes;
	}

}
